### ISSUE TITLE
Disable collision detection in generating scenes

### ISSUE THREAD

**Issue by abol-karimi** [BerkeleyLearnVerify/Scenic#103]
I need to generate scenarios where the vehicles can overlap (and pass through each other). With the 'allowCollisions' property I can let actors collide during the simulation, but Scenic still requires the initial generated scene to be collision-free. Is there a global parameter to disable collision-checking completely?

**Comment by Eric-Vin** [comment]
Hello!

The `allowCollisions` property  being set to true actually allows an object to intersect with others in initial scene generation, so it should be able to achieve what you're describing here. Scenic currently does not automatically check for collision during simulation, since it's assumed this will be handled by the simulator, though you can check intersection in requirements if needed. If your scenario is rejecting because of collisions and you have `allowCollisions` set to true for all relevant objects, please let me know as that is an issue. 

If you want a fast way to create objects with that can collide, I would create a subclass of Object with the property `allowCollisions` set to True, and then use that as a base for all further Scenic objects you create.

Hope this helps!
