### ISSUE TITLE
No module named 'scenic.simulators.newtonian'

### ISSUE THREAD

**Issue by MathildeJeannin** [BerkeleyLearnVerify/Scenic#108]
Hi, 

I am following the tutorials and in the Dynamic Scenarios part, when I try the following command :
scenic examples/driving/badlyParkedCarPullingIn.scenic \
    --simulate \
    --model scenic.simulators.newtonian.driving_model \
    --time 200

I got the following error : 
ModuleNotFoundError: No module named 'scenic.simulators.newtonian'

How is it possible ? I didn't modify a thing. 

Thank you !

**Comment by dfremont** [comment]
Hello Mathilde,

Which version of Python are you using, and how did you install Scenic? The error makes it look like something may be wrong with the installation. If you open a Python interpreter and try `import scenic.simulators.newtonian`, does that work?

**Comment by Kai-X-Org** [comment]
Hi, what I found is that if when using Python 3.8 in a conda virtual environment, installing scenic through pip installs everything except for the newtonian in the simulator directory.
At least on my machine (Mac), in an environment called scenicenv2, if I go to the directory

`anaconda3/envs/scenicenv2/lib/python3.8/site-packages/scenic/simulators`
I see that there is no folder called `newtonian`. So you can probably just manually add newtonian in there.

Also, I noticed that the `scenic` command only works in the command line if you downloaded scenic from python 3.8,
and that with other versions of python, you would end up downloading `scenic 1.1.0` rather than `scenic 2.0.0`. Hope this helps.

**Comment by dfremont** [comment]
Ah, yes, the Newtonian simulator was added in version 2.1.0, which is still in beta, so you won't get it if you install Scenic from PyPI, since `pip` doesn't install pre-release versions from PyPI unless you add the `--pre` option. We will try to put a new release on PyPI soon, but in the mean time I'd suggest either using the `--pre` option or cloning the Scenic repository and installing from there (following the instructions in our "Getting Started with Scenic" page).

**Comment by dfremont** [comment]
Version 2.1.0 is out of beta, so installing directly from PyPI will now give you a version including the Newtonian simulator even without the `--pre` option. The [installation instructions](https://scenic-lang.readthedocs.io/en/latest/quickstart.html) now describe in more detail the pros/cons of installing from PyPI vs. from the repository.
