### ISSUE TITLE
Syntax Highlighting in VSCode

### ISSUE THREAD

**Issue by abol-karimi** [BerkeleyLearnVerify/Scenic#135]
Feature request.

**Comment by dfremont** [comment]
Hello Abofazl, we plan to publish a VS Code extension for this soon (using the grammar [here](https://github.com/UCSCFormalMethods/Scenic-tmLanguage), which also works for Sublime Text). If you would like to try out the current prototype, I'm attaching it here: you can unzip it and use the "Install from VSIX" command under the Extensions drop-down menu to install it. Note that the default VS Code color theme does a poor job with it since it doesn't give operators a different color from ordinary text; some other themes like Monokai work better. Let me know if you have any feedback.

[Scenic-1.1.0.vsix.zip](https://github.com/BerkeleyLearnVerify/Scenic/files/11852595/Scenic-1.1.0.vsix.zip)

**Comment by abol-karimi** [comment]
Thanks a lot! It works perfectly fine with Atom One Dark Theme.

**Comment by dfremont** [comment]
The `Scenic` extension for VS Code is now available in the Marketplace: https://marketplace.visualstudio.com/items?itemName=UCSCFormalMethods.Scenic
